image: Visual Studio 2019
version: 0.0.{build}
build:
  verbosity: minimal
platform:
- x64
configuration:
- Release
before_build:
- nuget restore
after_build:
- cd PhotoTagger\bin\x64\Release\netcoreapp3.1
- del Xceed.Wpf.DataGrid.dll
- del Xceed.Wpf.Avalon*
- 7z a ..\..\..\..\..\PhotoTagger.zip *.exe *.dll *.config *.runtimeconfig.json
- cd ..\..\..\..\..\PhotoCull\bin\x64\Release\netcoreapp3.1
- 7z a ..\..\..\..\..\PhotoTagger.zip *.exe *.dll *.config *.runtimeconfig.json
artifacts:
- path: PhotoTagger.zip
  name: Zipped
deploy:
- provider: GitHub
  auth_token:
    secure: oy9vmWoKGVoCQo1SmAaMu/j8ZEBCMCr7jbkPQ0CdJVwaY0MNwYqi/yqHlH6DIoFG
  artifact: Zipped
  on:
    appveyor_repo_tag: true
